name: widget_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  desktop_multi_window: ^0.2.0
  flutter:
    sdk: flutter
  flutter_lucide: ^1.5.0
  go_router: ^14.2.7
  rive: ^0.13.18
  shared_preferences: ^2.3.3
  window_manager: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: false
  assets:
    - assets/rive/
  fonts:
    - family: GeneralSans
      fonts:
        - asset: assets/fonts/GeneralSans-Variable.ttf
          weight: 700
        - asset: assets/fonts/GeneralSans-VariableItalic.ttf
          style: italic
    - family: Supreme
      fonts:
        - asset: assets/fonts/Supreme-Variable.ttf
          weight: 700
        - asset: assets/fonts/Supreme-VariableItalic.ttf
          style: italic