name: widget_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  desktop_multi_window: ^0.2.0
  flutter:
    sdk: flutter
  go_router: ^14.2.7
  window_manager: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
